services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    mem_limit: 256m
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-almas98abolfazl}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-almas98abolfazl}?schema=public
      PORT: 3000
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  frontend-site:
    build:
      context: ./frontend-site
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"  # ◄◄ پورت ویندوز تغییر کرد به 8080 تا با پورت 80 سیستم خودت تداخل نداشته باشد
    depends_on:
      - backend
    networks:
      - app-network

  frontend-admin:
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
    restart: unless-stopped
    # ◄◄ نیازی به باز کردن پورت مستقیم برای ادمین نیست، چون ترافیک از طریق Nginx کانتینر بالا (پورت 8080) با پچ /admin روت می‌شود.
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge